//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntAssign
    {
        public int IntAssignId { get; set; }
        public int InterviewId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Interview Interview { get; set; }
        public virtual User User { get; set; }
    }
}
