//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.AppAnswers = new HashSet<AppAnswer>();
        }
    
        public int QuestionId { get; set; }
        public string QuestionType { get; set; }
        public string Question1 { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Answer1 { get; set; }
        public bool Answer1State { get; set; }
        public string Answer2 { get; set; }
        public bool Answer2State { get; set; }
        public string Answer3 { get; set; }
        public bool Answer3State { get; set; }
        public string Answer4 { get; set; }
        public bool Answer4State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppAnswer> AppAnswers { get; set; }
        public virtual User User { get; set; }
    }
}
