//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int UserLoginId { get; set; }
        public int UserIdLogin { get; set; }
        public string Name { get; set; }
        public Nullable<bool> isAdmin { get; set; }
        public Nullable<bool> isInterviewer { get; set; }
        public Nullable<bool> isReceiptionist { get; set; }
        public Nullable<bool> isApplicant { get; set; }
        public string LoginUsername { get; set; }
        public string LoginPassword { get; set; }
    }
}
